language: node_js
cache: yarn
script:
  - yarn --version
  - yarn check --integrity
  - yarn setup
  - yarn lint
  - yarn test
  - yarn test:a11y
  - yarn test-coverage-report
after_success:
  - yarn test:codacy-upload
  - yarn test:codecov-upload
