language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
node_js:
  - "10.15.3"
cache: yarn
script:
  - yarn check --integrity
  - yarn add puppeteer
  - yarn lint
  - yarn build
  - yarn test:express
  - yarn test:angular
  - yarn test:a11y
after_success:
  - yarn test:coverage
  - yarn sonar-scan
