language: node_js
node_js:
  - "node"
cache: yarn
script:
  - yarn check --integrity
  - yarn add puppeteer
  - yarn lint
  - yarn build
  - yarn test:nsp
  - yarn test:express
  - yarn test:angular
  - yarn test:a11y
after_success:
  - yarn test:coverage
  - yarn sonar-scan
