language: node_js
cache: yarn
script:
  - yarn --version
  - yarn check --integrity
  - yarn build
  - yarn test:nsp
  - yarn lint 
  - yarn test:nsp 
  - yarn test:express 
  - yarn test:angular 
  - yarn test:a11y
after_success:
  - yarn test:coverage 
  - yarn sonar-scan
