apiVersion: v2
appVersion: "2.0"
description: Helm chart for the HMCTS bar web
name: bar-web
home: https://github.com/hmcts/bar-web
version: 0.0.6
maintainers:
  - name: HMCTS Bar Dev Team
    email: bar@hmcts.net
dependencies:
  - name: nodejs
    version: 2.4.0
    repository: '@hmctspublic'
  - name: idam-pr
    version: ~2.2.6
    repository: '@hmctspublic'
    condition: idam-pr.enabled
