nodejs:
  image: hmctspublic.azurecr.io/bar/web:latest
  ingressHost: bar.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 3000
  aadIdentityName: bar
  environment:
    BAR_API_URL: http://bar-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FEE_API_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/fees-register
    FEE_API_JURISDICTIONS_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_LOGIN_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o/authorize
    IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
  keyVaults:
    bar:
      secrets:
        - bar-IDAM-CLIENT-SECRET
        - AppInsightsInstrumentationKey

idam-pr:
  enabled: false
