nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.aat.platform.hmcts.net/login
    BAR_API_URL: http://${SERVICE_NAME}-bar-api
    IDAM_CLIENT_SECRET: ${IDAM_CLIENT_SECRET}
bar-api:
  releaseNameOverride: ${SERVICE_NAME}-bar-api
  java:
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}
    aadIdentityName:
    environment:
      #SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-bar-db:5432/bar"
      POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
      POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
      POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
      POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
      POSTGRES_CONNECTION_OPTIONS: "?sslmode=allow"
      SPRING_LIQUIBASE_ENABLED: true
    postgresql:
      postgresqlUsername: bar
      postgresqlPassword: bar
      postgresqlDatabase: bar
      keyVaults:
        "bar":
          secrets:
            - bar-S2S-SECRET
  postgresql:
    enabled: true
