protocol: http
security:
  referrerPolicy: origin
idam:
  client_id: bar_frontend
  login_url: https://idam-web-public.demo.platform.hmcts.net/login
  api_url: https://idam-api.demo.platform.hmcts.net
session:
  cookieName: BAR
s2s:
  url: http://rpe-service-auth-provider-demo.service.core-compute-demo.internal
bar:
  url: http://localhost:80
  defaultPort: 3000
  microservice: bar_frontend
fee:
  url: http://fees-register-api-demo.service.core-compute-demo.internal/fees-register
  jurisdictionsUrl: http://fees-register-api-demo.service.core-compute-demo.internal
certs:
  crt: ./dev-certificates/localhost.cert
  key: ./dev-certificates/localhost.key
appInsights:
  instrumentationKey: some-key
e2e:
  frontendUrl: http://localhost:3000
  barApiUrl: http://bar-api-demo.service.core-compute-demo.internal
  proxyUrl: http://proxyout.reform.hmcts.net:8080
  waitForTimeoutValue: 2600
  waitForActionValue: 2000
site_api:
  url: http://localhost:80

