'use strict';
//  in this file you can append custom step methods to 'I' object
const faker = require('faker');

const ChequePayername = faker.name.firstName();
const PostalOrderPayername = faker.name.firstName();
const CashPayername = faker.name.firstName();
const AllPayPayername = faker.name.firstName();
const CardPayername = faker.name.firstName();
const EditPayername = faker.name.firstName();
const addContext = require('mochawesome/addContext');

addContext('simple string');

const waitTime = 2;
const waitTimeFive = 2;
const waitTimeForElement = 30;
const waitTimeForText = 10;

module.exports = () => {
  return ({
    login: (email, password) => {
      faker.fillField('Email address', email);
      faker.fillField('Password', password);
      faker.waitForElement({ css: '[type="submit"]' }, waitTimeForElement);
      faker.click({ css: '[type="submit"]' });
    },
    paymentTypeCheque: () => {
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div[1]/fieldset/div/div[1]/label/div/input' }, waitTimeForElement);
      faker.click({ xpath: '//div[1]/fieldset/div/div[1]/label/div/input' });
      faker.wait(waitTime);
      faker.see('Cheque number');
      faker.fillField('Payer name', ChequePayername);
      faker.fillField('Amount', '550');
      faker.fillField('Cheque number', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.waitForVisible('.govuk-box-highlight');
      faker.see('Add Payment Instruction');
      faker.see('Payment information added');
      faker.click({ css: '.column-one-half>p>a' });
      //  faker.click({ css: '.modal-link' });
      //  faker.click('Check and submit');
      faker.waitForText(ChequePayername, waitTimeForText);
      faker.see('ID');
      faker.see('Date');
      faker.see('Payer name');
      faker.see('Payment type');
      faker.see('Amount');
      faker.see('Payment Reference');
      faker.see('Status');
      faker.see('Select');
      faker.see('All');
      faker.see('Payments Log');
      faker.see('To Check');
      faker.see('Submitted');
      faker.seeElement('.gray:disabled');
      faker.seeElement('.green:disabled');
      faker.waitForText(ChequePayername, waitTimeForText);
      faker.see(ChequePayername);
    },
    paymentTypePostalOrder: () => {
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div[1]/fieldset/div/div[2]/label/div/input' }, waitTimeForElement);
      faker.wait(waitTime);
      faker.click({ xpath: '//div[1]/fieldset/div/div[2]/label/div/input' });
      faker.wait(waitTime);
      faker.see('Postal order number');
      faker.fillField('Payer name', PostalOrderPayername);
      faker.fillField('Amount', '550');
      faker.fillField('Postal order number', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.waitForVisible('.govuk-box-highlight');
      faker.see('Add Payment Instruction');
      faker.see('Payment information added');
      faker.click({ css: '.column-one-half>p>a' });
      // faker.waitForVisible('.modal-window');
      // faker.click({ css: '.modal-link' });
      // faker.click('Check and submit');
      faker.waitForText(PostalOrderPayername, waitTimeForText);
      faker.see('ID');
      faker.see('Date');
      faker.see('Payer name');
      faker.see('Payment type');
      faker.see('Amount');
      faker.see('Payment Reference');
      faker.see('Status');
      faker.see('Select');
      faker.see('All');
      faker.see('Payments Log');
      faker.see('To Check');
      faker.see('Submitted');
      faker.seeElement('.gray:disabled');
      faker.seeElement('.green:disabled');
      faker.waitForText(PostalOrderPayername, waitTimeForText);
      faker.see(PostalOrderPayername);
    },
    paymentTypeCash: () => {
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div[1]/fieldset/div/div[3]/label/div/input' }, waitTimeForElement);
      faker.click({ xpath: '//div[1]/fieldset/div/div[3]/label/div/input' });
      faker.wait(waitTime);
      //  faker.see('Cash');
      faker.fillField('Payer name', CashPayername);
      faker.fillField('Amount', '550');
      //  faker.fillField('Postal order number', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.waitForVisible('.govuk-box-highlight');
      faker.see('Add Payment Instruction');
      faker.see('Payment information added');
      faker.click({ css: '.column-one-half>p>a' });
      // faker.waitForVisible('.modal-window');
      // faker.click({ css: '.modal-link' });
      // faker.click('Check and submit');
      faker.waitForText(CashPayername, waitTimeForText);
      faker.see('ID');
      faker.see('Date');
      faker.see('Payer name');
      faker.see('Payment type');
      faker.see('Amount');
      faker.see('Payment Reference');
      faker.see('Status');
      faker.see('Select');
      faker.see('All');
      faker.see('Payments Log');
      faker.see('To Check');
      faker.see('Submitted');
      faker.seeElement('.gray:disabled');
      faker.seeElement('.green:disabled');
      faker.waitForText(CashPayername, waitTimeForText);
      faker.see(CashPayername);
    },
    paymentTypeAllPay: () => {
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div[1]/fieldset/div/div[4]/label/div/input' }, waitTimeForElement);
      faker.click({ xpath: '//div[1]/fieldset/div/div[4]/label/div/input' });
      faker.wait(waitTime);
      faker.see('AllPay transaction ID');
      faker.fillField('Payer name', AllPayPayername);
      faker.fillField('Amount', '550');
      faker.fillField('AllPay transaction ID', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.waitForVisible('.govuk-box-highlight');
      faker.see('Add Payment Instruction');
      faker.see('Payment information added');
      faker.click({ css: '.column-one-half>p>a' });
      // faker.waitForVisible('.modal-window');
      // faker.click({ css: '.modal-link' });
      // faker.click('Check and submit');
      faker.waitForText(AllPayPayername, waitTimeForText);
      faker.see('ID');
      faker.see('Date');
      faker.see('Payer name');
      faker.see('Payment type');
      faker.see('Amount');
      faker.see('Payment Reference');
      faker.see('Status');
      faker.see('Select');
      faker.see('All');
      faker.see('Payments Log');
      faker.see('To Check');
      faker.see('Submitted');
      faker.seeElement('.gray:disabled');
      faker.seeElement('.green:disabled');
      faker.waitForText(AllPayPayername, waitTimeForText);
      faker.see(AllPayPayername);
    },
    paymentTypeCard: () => {
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div[1]/fieldset/div/div[5]/label/div/input' }, waitTimeForElement);
      faker.click({ xpath: '//div[1]/fieldset/div/div[5]/label/div/input' });
      faker.wait(waitTime);
      faker.waitForText('Authorization Code', waitTimeForText);
      faker.see('Authorization Code');
      faker.fillField('Payer name', CardPayername);
      faker.fillField('Amount', '550');
      faker.fillField('Authorization Code', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.waitForVisible('.govuk-box-highlight');
      faker.see('Add Payment Instruction');
      faker.see('Payment information added');
      faker.click({ css: '.column-one-half>p>a' });
      faker.wait(waitTime);
      // faker.waitForVisible('.modal-window');
      // faker.click({ css: '.modal-link' });
      // faker.click('Check and submit');
      faker.waitForText(CardPayername, waitTimeForText);
      faker.see('ID');
      faker.see('Date');
      faker.see('Payer name');
      faker.see('Payment type');
      faker.see('Amount');
      faker.see('Payment Reference');
      faker.see('Status');
      faker.see('Select');
      faker.see('All');
      faker.see('Payments Log');
      faker.see('To Check');
      faker.see('Submitted');
      faker.seeElement('.gray:disabled');
      faker.seeElement('.green:disabled');
      faker.waitForText(CardPayername, waitTimeForText);
      faker.see(CardPayername);
    },

    editPayerNameAmountAndAuthorizationCode: () => {
      faker.waitForText('Check and submit', waitTimeForText);
      //   faker.waitForElement({ xpath: '//div[2]/div/ul/li[2]/a' }, waitTimeForElement);
      faker.click('Check and submit');
      faker.wait(waitTimeFive);
      faker.waitForElement({ xpath: '//div/table/tbody[1]/tr/td[1]/a' }, waitTimeForElement);
      faker.click({ xpath: '//div/table/tbody[1]/tr/td[1]/a' });
      faker.waitForText('Authorization Code', waitTimeForText);
      faker.see('Authorization Code');
      faker.fillField('Payer name', EditPayername);
      faker.fillField('Amount', '10000');
      faker.fillField('Authorization Code', '123456');
      faker.click({ css: '[type="submit"]' });
      //   faker.waitForVisible('.govuk-box-highlight');
      //  faker.see('Add Payment Instruction');
      //  faker.see('Payment information added');
      //  faker.click({ css: '.column-one-half>p>a' });
      // faker.waitForVisible('.modal-window');
      // faker.click({ css: '.modal-link' });
      // faker.click('Check and submit');
      faker.waitForText(EditPayername, waitTimeForText);
      faker.see('ID');
      faker.see('Date');
      faker.see('Payer name');
      faker.see('Payment type');
      faker.see('Amount');
      faker.see('Payment Reference');
      faker.see('Status');
      faker.see('Select');
      faker.see('All');
      faker.see('Payments Log');
      faker.see('Submitted');
      faker.see('10,000');
      faker.see('123456');
      faker.seeElement('.gray:disabled');
      faker.seeElement('.green:disabled');
      faker.waitForText(EditPayername, waitTimeForText);
      faker.see(EditPayername);
    },

    deletePaymentInformation: () => {
      faker.waitForText('Check and submit');
      faker.click('Check and submit');
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div[2]/div/div/div/input' }, waitTimeForElement);
      faker.click({ xpath: '//div/table/tbody/tr/td[8]/div/input' });
      faker.wait(waitTime);
      faker.click('Delete');
      faker.wait(waitTime);
      faker.see(0);
    },

    submitAllPaymentInformation: () => {
      faker.waitForElement({ xpath: '//div[2]/div/ul/li[2]/a' }, waitTimeForElement);
      faker.click({ xpath: '//div[2]/div/ul/li[2]/a' });
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div/div[1]/div[2]/div[2]/div/button[2]' }, waitTimeForElement);
      faker.seeElement('.gray:disabled');
      faker.seeElement('.green:disabled');
      faker.click({ xpath: '//div[2]/div/div/div/input' });
      faker.wait(waitTime);
      faker.seeElement('.green:enabled');
      faker.waitForElement({ xpath: '//div/div[1]/div[2]/div[2]/div/button[2]' }, waitTimeForElement);
      faker.click({ xpath: '//div/div[1]/div[2]/div[2]/div/button[2]' });
      faker.wait(waitTime);
      faker.seeElement('.gray:disabled');
      faker.seeElement('.green:disabled');

      //   addContext(this, 'http:// www.url.com/screenshot-maybe.jpg');
      //  faker.addMochawesomeContext('output');
    },
    feeclerkChequePaymentType: () => {
      faker.wait(waitTimeFive);
      faker.waitForText('Payment Type', waitTimeForText);
      faker.click({ xpath: '//div[1]/fieldset/div/div[1]/label/div/input' });
      faker.see('Cheque');
      faker.fillField('Payer name', ChequePayername);
      faker.fillField('Amount', '550');
      faker.fillField('Cheque number', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.wait(waitTime);
      faker.waitForVisible('.govuk-box-highlight');
      faker.click({ css: '.button.button-cancel' });
      faker.wait(waitTime);
      faker.waitForText(ChequePayername, waitTimeForText);
      faker.see('Validate payment');
      faker.see('No fee details on payment');
      faker.see('Payment details');
      faker.click({ xpath: '//div/div[2]/div[2]/button' });
      faker.fillField('Case number', '654321');
      faker.fillField('Search for a Fee', 'fees order 1.2');
      faker.wait(waitTime);
      faker.click({ xpath: '//div[5]/table/tbody/tr/td[4]/a' });
      faker.wait(waitTime);
      faker.click('Save');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/select' });
      faker.waitForElement({ xpath: '//div/div[1]/div[2]/div/div/select' }, waitTimeForElement);
      faker.wait(waitTime);
      faker.selectOption('//div/div[1]/div[2]/div/div/select', 'Process');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/input' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div[2]/div/ul[1]/li[3]/a' });
      faker.wait(waitTime);
      faker.see(ChequePayername);
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/table/thead/tr/th[11]/div' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/div/p/a' });
      faker.see('Check and submit');
      faker.wait(waitTime);
      faker.see(0);
    },
    feeclerkPostalOrderPaymentType: () => {
      faker.wait(waitTimeFive);
      faker.waitForText('Payment Type', waitTimeForText);
      //   faker.waitForElement({ xpath: '//div[1]/fieldset/div/div[2]/label/div/input' }, waitTimeForElement);
      faker.click({ xpath: '//div[1]/fieldset/div/div[2]/label/div/input' });
      faker.see('Postal order number');
      faker.fillField('Payer name', PostalOrderPayername);
      faker.fillField('Amount', '550');
      faker.fillField('Postal order number', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.wait(waitTime);
      faker.waitForVisible('.govuk-box-highlight');
      faker.click({ css: '.button.button-cancel' });
      faker.wait(waitTime);
      faker.waitForText(PostalOrderPayername, waitTimeForText);
      faker.see('Validate payment');
      faker.see('No fee details on payment');
      faker.see('Payment details');
      faker.click({ xpath: '//div/div[2]/div[2]/button' });
      faker.fillField('Case number', '654321');
      faker.fillField('Search for a Fee', 'fees order 1.2');
      faker.wait(waitTime);
      faker.click({ xpath: '//div[5]/table/tbody/tr/td[4]/a' });
      faker.wait(waitTime);
      faker.click('Save');
      //   faker.click({ xpath: '//div/div/form/div[11]/button' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/select' });
      faker.waitForElement({ xpath: '//div/div[1]/div[2]/div/div/select' }, waitTimeForElement);
      faker.wait(waitTime);
      faker.selectOption('//div/div[1]/div[2]/div/div/select', 'Process');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/input' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div[2]/div/ul[1]/li[3]/a' });
      faker.wait(waitTime);
      faker.see(PostalOrderPayername);
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/table/thead/tr/th[11]/div' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/div/p/a' });
      faker.see('Check and submit');
      faker.see(0);
    },

    feeclerkCashPaymentType: () => {
      faker.wait(waitTimeFive);
      faker.waitForText('Payment Type', waitTimeForText);
      faker.click({ xpath: '//div[1]/fieldset/div/div[3]/label/div/input' });
      faker.fillField('Payer name', CashPayername);
      faker.fillField('Amount', '550');
      faker.click({ css: '[type="submit"]' });
      faker.waitForVisible('.govuk-box-highlight');
      faker.click({ css: '.button.button-cancel' });
      faker.waitForText(CashPayername, waitTimeForText);
      faker.see('Validate payment');
      faker.see('No fee details on payment');
      faker.see('Payment details');
      faker.click({ xpath: '//div/div[2]/div[2]/button' });
      faker.fillField('Case number', '654321');
      faker.fillField('Search for a Fee', 'fees order 1.2');
      faker.wait(waitTimeFive);
      faker.click({ xpath: '//div[5]/table/tbody/tr/td[4]/a' });
      faker.wait(waitTime);
      faker.click('Save');
      //  faker.click({ xpath: '//div/div/form/div[11]/button' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/select' });
      faker.waitForElement({ xpath: '//div/div[1]/div[2]/div/div/select' }, waitTimeForElement);
      faker.wait(waitTime);
      faker.selectOption('//div/div[1]/div[2]/div/div/select', 'Process');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/input' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div[2]/div/ul[1]/li[3]/a' });
      faker.wait(waitTime);
      faker.see(CashPayername);
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/table/thead/tr/th[11]/div' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/div/p/a' });
      faker.see('Check and submit');
      faker.see(0);
    },

    feeclerkAllPayPaymentType: () => {
      faker.wait(waitTimeFive);
      faker.waitForText('Payment Type', waitTimeForText);
      faker.click({ xpath: '//div[1]/fieldset/div/div[4]/label/div/input' });
      faker.see('AllPay transaction ID');
      faker.fillField('Payer name', AllPayPayername);
      faker.fillField('Amount', '550');
      faker.fillField('AllPay transaction ID', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.waitForVisible('.govuk-box-highlight');
      faker.click({ css: '.button.button-cancel' });
      faker.waitForText(AllPayPayername, waitTimeForText);
      faker.see('Validate payment');
      faker.see('No fee details on payment');
      faker.see('Payment details');
      faker.click({ xpath: '//div/div[2]/div[2]/button' });
      faker.fillField('Case number', '654321');
      faker.fillField('Search for a Fee', 'fees order 1.2');
      faker.wait(waitTime);
      faker.click({ xpath: '//div[5]/table/tbody/tr/td[4]/a' });
      faker.wait(waitTime);
      faker.click('Save');
      //  faker.click({ xpath: '//div/div/form/div[11]/button' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/select' });
      faker.waitForElement({ xpath: '//div/div[1]/div[2]/div/div/select' }, waitTimeForElement);
      faker.wait(waitTime);
      faker.selectOption('//div/div[1]/div[2]/div/div/select', 'Process');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/input' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div[2]/div/ul[1]/li[3]/a' });
      faker.wait(waitTime);
      faker.see(AllPayPayername);
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/table/thead/tr/th[11]/div' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/div/p/a' });
      faker.see('Check and submit');
      faker.see(0);
    },

    feeclerkCardPaymentType: () => {
      faker.wait(waitTimeFive);
      faker.waitForText('Payment Type', waitTimeForText);
      faker.click({ xpath: '//div[1]/fieldset/div/div[5]/label/div/input' });
      faker.see('Authorization Code');
      faker.fillField('Payer name', CardPayername);
      faker.fillField('Amount', '550');
      faker.fillField('Authorization Code', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.waitForVisible('.govuk-box-highlight');
      faker.click({ css: '.button.button-cancel' });
      faker.waitForText(CardPayername, waitTimeForText);
      faker.see('Validate payment');
      faker.see('No fee details on payment');
      faker.see('Payment details');
      faker.click({ xpath: '//div/div[2]/div[2]/button' });
      faker.fillField('Case number', '654321');
      faker.fillField('Search for a Fee', 'fees order 1.2');
      faker.wait(waitTime);
      faker.click({ xpath: '//div[5]/table/tbody/tr/td[4]/a' });
      faker.wait(waitTime);
      faker.click('Save');
      //   faker.click({ xpath: '//div/div/form/div[11]/button' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/select' });
      faker.waitForElement({ xpath: '//div/div[1]/div[2]/div/div/select' }, waitTimeForElement);
      faker.wait(waitTime);
      faker.selectOption('//div/div[1]/div[2]/div/div/select', 'Process');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/input' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div[2]/div/ul[1]/li[3]/a' });
      faker.wait(waitTime);
      faker.see(CardPayername);
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/table/thead/tr/th[11]/div' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/div/p/a' });
      faker.see('Check and submit');
      faker.see(0);
    },
    feeclerkEditChequePaymentType: () => {
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div[1]/fieldset/div/div[1]/label/div/input' }, waitTimeForElement);
      faker.click({ xpath: '//div[1]/fieldset/div/div[1]/label/div/input' });
      faker.wait(waitTime);
      faker.see('Cheque number');
      faker.fillField('Payer name', ChequePayername);
      faker.fillField('Amount', '550');
      faker.fillField('Cheque number', '312323');
      faker.click({ css: '[type="submit"]' });
      faker.wait(waitTime);
      faker.waitForVisible('.govuk-box-highlight');
      faker.click({ css: '.button.button-cancel' });
      faker.waitForText(ChequePayername, waitTimeForText);
      faker.see('Validate payment');
      faker.see('No fee details on payment');
      faker.see('Payment details');
      faker.wait(waitTimeFive);
      faker.click({ xpath: '//div/div[4]/table/tbody/tr/td[7]/a' });
      //   faker.see('Cheque number');
      faker.wait(waitTimeFive);
      faker.fillField('Payer name', EditPayername);
      faker.fillField('Amount', '10000');
      faker.fillField('Cheque number', '123456');
      faker.click({ css: '[type="submit"]' });
      faker.wait(waitTime);
      faker.click('Payments list');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[3]/div/div/table/tbody[1]/tr/td[1]/a' });
      faker.wait(waitTime);
      faker.waitForText(EditPayername, waitTimeForText);
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div[2]/button' });
      faker.fillField('Case number', '654321');
      faker.fillField('Search for a Fee', 'fees order 1.2');
      faker.wait(waitTime);
      faker.click({ xpath: '//div[5]/table/tbody/tr/td[4]/a' });
      faker.wait(waitTimeFive);
      faker.click('Save');
      //   faker.click({ xpath: '//div/div/form/div[11]/button' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[5]/table/tbody/tr/td[6]/button' });
      faker.fillField('Case number', '7657676');
      faker.click({ xpath: '//div/div/form/div[6]/div[1]/div[2]/a' });
      faker.fillField('Search for a Fee', 'Recovery of Land - High Court');
      faker.wait(waitTimeFive);
      faker.click({ xpath: '//div/div/form/div[5]/table/tbody/tr/td[4]/a' });
      faker.wait(waitTime);
      faker.click('Save');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[5]/table/tbody/tr/td[6]/div/a' });
      faker.wait(waitTimeFive);
      faker.waitForText(EditPayername, waitTimeForText);
      faker.click({ xpath: '//div/div[2]/div[2]/button' });
      faker.wait(waitTime);
      faker.fillField('Case number', '654321');
      faker.fillField('Search for a Fee', 'Claim Amount - Unspecified');
      faker.wait(waitTimeFive);
      faker.click({ xpath: '//div/div/form/div[5]/table/tbody/tr/td[4]/a' });
      faker.wait(waitTime);
      faker.click('Save');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/select' });
      faker.waitForElement({ xpath: '//div/div[1]/div[2]/div/div/select' }, waitTimeForElement);
      faker.wait(waitTime);
      faker.selectOption('//div/div[1]/div[2]/div/div/select', 'Process');
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[1]/div[2]/div/div/input' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div[2]/div/ul[1]/li[3]/a' });
      faker.wait(waitTime);
      faker.see(EditPayername);
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/table/thead/tr/th[11]/div' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div/div[2]/div/div/p/a' });
      faker.see('Check and submit');
      faker.see(0);
    },
    SeniorFeeClerkCardPaymentType: () => {
      faker.waitForText('Anish Fee Clerk Anish Fee Clerk', waitTimeForText);
      //  faker.waitForElement({ xpath: '// th/a' }, waitTimeForElement);
      faker.seeElement({ xpath: '// th/a' });
      faker.wait(waitTimeFive);
      faker.click('Anish Fee Clerk Anish Fee Clerk');
      faker.waitForText(ChequePayername, waitTimeForText);
      faker.waitForElement({ xpath: '//div/table/thead/tr/th[11]/div/input' }, waitTimeForElement);
      faker.click({ xpath: '//div/table/thead/tr/th[11]/div/input' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div[2]/button[2]' });
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div[3]/p/a' }, waitTimeForElement);
      faker.click({ xpath: '//div[2]/div[3]/p/a' });
      faker.wait(waitTime);
      faker.seeElement({ xpath: '// th/a' });
    },
    DeliveryManagerTransferToBAR: () => {
      faker.wait(waitTimeFive);
      faker.waitForElement({ xpath: '//div/table/tbody/tr[1]/th/a' }, waitTimeForElement);
      faker.seeElement({ xpath: '//div/table/tbody/tr[1]/th/a' });
      faker.wait(waitTimeFive);
      faker.click('ViswaSenior Fee Clerk Viswa Senior Fee Clerk');
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div/table/thead/tr/th[11]/div/input' }, waitTimeForElement);
      faker.click({ xpath: '//div/table/thead/tr/th[11]/div/input' });
      faker.wait(waitTime);
      faker.click({ xpath: '//div[2]/button[2]' });
      faker.wait(waitTime);
      faker.waitForElement({ xpath: '//div[3]/p/a' }, waitTimeForElement);
      faker.click({ xpath: '//div[3]/p/a' });
      faker.wait(waitTime);
      faker.seeElement({ xpath: '// tr[2]/th/a' });
    }
  });
};
