product_url = "bar.aat.platform.hmcts.net"
capacity = "2"
idam_api_url = "https://idam-api.aat.platform.hmcts.net"
authentication_web_url = "https://idam-web-public.aat.platform.hmcts.net/login"
vault_section = "preprod"
