product_url = "bar.demo.platform.hmcts.net"
idam_api_url = "https://idam-api.demo.platform.hmcts.net"
authentication_web_url = "https://idam-web-public.demo.platform.hmcts.net/login"
capacity = "1"
vault_section = "preprod"
